@DECT_Api_HostAddress = https://localhost:5001

GET {{DECT_Api_HostAddress}}/api/mongodb/latest
Accept: application/json

###

GET {{DECT_Api_HostAddress}}/api/mongodb/all-tx-ids
Accept: application/json

###

GET {{DECT_Api_HostAddress}}/api/mongodb/latest/20
Accept: application/json

###

GET {{DECT_Api_HostAddress}}/api/mongodb/latest/0xaabbccdd/20
Accept: application/json

###